import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
      <html lang="en">
        <body className="flex flex-col justify-between items-center h-screen pt-14 pb-10 bg-gradient-to-b from-gray-900 to-gray-600 bg-gradient-to-r font-dosis">
          <h1 className="text-6xl font-bold text-white">Next Quiz</h1>
            {children}
          <p className="text-2xl font-semibold text-white ">A quiz app built with Next.js</p>
        </body>
      </html>
  )
}
